services:
  node:
    environment:
      YARN_CACHE_FOLDER: '/home/yarn-cache'
    image: node:18
    user: '${HOST_USER_IDS:-1000:1000}'
    volumes:
      - '.:/srv/app'
      - '${HOST_YARN_CACHE_FOLDER:-~/.cache/yarn}:/home/yarn-cache'
      - '${HOST_YARN_CONFIG_FOLDER:-~/.yarn}:/.yarn'
      - '${HOST_YARN_CONFIG_FILE:-~/.yarnrc}:/.yarnrc'
    working_dir: '/srv/app'
