x-common: &common
  image: node:${NODE_VERSION}
  restart: always
  user: ${HOST_USER_IDS:-1000:1000}
  volumes:
    - .:/srv/app
  working_dir: /srv/app

services:
  devcontainer:
    build:
      args:
        NODE_VERSION: ${NODE_VERSION}
      context: ./docker/devcontainer
    command:
      - sleep
      - infinity
    environment:
      YARN_CACHE_FOLDER: /home/yarn-cache
    user: ${HOST_USER_IDS:-1000:1000}
    volumes:
      - type: bind
        source: .
        target: /srv/app
      - type: bind
        source: ${HOST_YARN_CACHE_FOLDER:-~/.cache/yarn}
        target: /home/yarn-cache
      - type: bind
        source: ${HOST_YARN_CONFIG_FOLDER:-~/.config/yarn}
        target: /.yarn
      - type: bind
        source: ${HOST_YARN_CONFIG_FILE:-~/.yarnrc}
        target: /.yarnrc
    working_dir: /srv/app

  dev:
    <<: *common
    command: yarn dev --host
    expose:
      - 5173
    ports:
      - 5173:5173

  prod:
    <<: *common
    command: sh -c "yarn build && yarn preview --host"
    expose:
      - 4173
    ports:
      - 4173:4173
