x-common: &common
  image: node:18
  restart: always
  user: ${HOST_USER_IDS:-1000:1000}
  volumes:
    - .:/srv/app
  working_dir: /srv/app

services:
  dev:
    <<: *common
    command: yarn dev --host
    expose:
      - 5173
    ports:
      - 5173:5173

  prod:
    <<: *common
    command: sh -c "yarn build && yarn preview --host"
    expose:
      - 4173
    ports:
      - 4173:4173
