version: 2.1

workflows:
  pull_request:
    jobs:
      - tests:
          context:
            - docker-hub-credentials
          filters:
            branches:
              ignore:
                - main

jobs:
  tests:
    machine:
      image: ubuntu-2204:2024.11.1
    steps:
      - checkout
      - set_host_user_ids_environment_variable
      - run:
          name: Setup cache directory
          command: ./.devcontainer/setup.sh
      - run:
          name: Install the latest Task binary
          command: npm install -g @go-task/cli
      - restore_cache:
          keys:
            - npm-{{ .Environment.CACHE_VERSION }}-{{ checksum "package-lock.json" }}
            - npm-{{ .Environment.CACHE_VERSION }}-
      - run:
          name: Install dependencies
          command: |
            task dependencies:install
      - save_cache:
          key: npm-{{ .Environment.CACHE_VERSION }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Check the code formatting
          command: task tests:static:format:check
      - run:
          name: Lint the style sheets
          command: task tests:static:style-sheet:lint
      - run:
          name: Lint the application code
          command: task tests:static:code:lint -- --format=junit -o test_results/eslint.xml
      - store_artifacts:
          path: test_results
      - store_test_results:
          path: test_results

commands:
  set_host_user_ids_environment_variable:
    description: "Set Docker Compose HOST_USER_IDS environment variable according to the host virtual machine"
    steps:
      - run:
          name: Set Docker Compose HOST_USER_IDS environment variable according to the host virtual machine
          command: |
            echo 'export HOST_USER_IDS="$(id -u):$(id -g)"' >> $BASH_ENV
